In [1]:
import pandas as pd

## Part 1 – Load the Data

In [2]:
export_df = pd.read_csv("Coffee_export.csv")
import_df = pd.read_csv("Coffee_import.csv")
production_df = pd.read_csv("Coffee_production.csv")

In [3]:
export_df.head()
import_df.head()
production_df.head()

,Country,Coffee type,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,Total_production
0,Angola,Robusta/Arabica,3.000000e+06,4.740000e+06,4.680000e+06,1.980000e+06,4.620000e+06,3.720000e+06,4.260000e+06,3.840000e+06,...,1.740000e+06,1.980000e+06,2.100000e+06,2.340000e+06,2.460000e+06,2.700000e+06,2.100000e+06,2.520000e+06,3.120000e+06,8.208000e+07
1,Bolivia (Plurinational State of),Arabica,7.380000e+06,6.240000e+06,7.200000e+06,3.060000e+06,7.020000e+06,8.520000e+06,7.500000e+06,8.460000e+06,...,7.920000e+06,6.300000e+06,7.200000e+06,6.000000e+06,5.040000e+06,4.680000e+06,5.040000e+06,4.980000e+06,4.860000e+06,2.070000e+08
2,Brazil,Arabica/Robusta,1.637160e+09,1.637580e+09,2.076180e+09,1.690020e+09,1.691520e+09,1.083600e+09,1.751820e+09,1.568880e+09,...,2.915520e+09,3.325080e+09,3.281340e+09,3.198300e+09,3.172260e+09,3.407280e+09,3.164400e+09,3.907860e+09,3.492660e+09,7.508298e+10
3,Burundi,Arabica/Robusta,2.922000e+07,4.002000e+07,3.720000e+07,2.358000e+07,3.984000e+07,2.604000e+07,2.406000e+07,1.500000e+07,...,1.224000e+07,2.436000e+07,9.780000e+06,1.488000e+07,1.614000e+07,1.176000e+07,1.212000e+07,1.224000e+07,1.632000e+07,6.236400e+08
4,Ecuador,Arabica/Robusta,9.024000e+07,1.274400e+08,7.110000e+07,1.241400e+08,1.425600e+08,1.132800e+08,1.195800e+08,7.146000e+07,...,4.950000e+07,4.968000e+07,3.996000e+07,3.864000e+07,3.864000e+07,3.870000e+07,3.744000e+07,2.976000e+07,3.354000e+07,1.900380e+09

## Part 2 – Explore the Data
How many rows and columns does the dataset contain?
    - 55 ros 33 columns

What are the column names?
    - Country, Coffee type, 1990/91 -> 2019/20 9 30 year columns, Total_production 

What data types are assigned to each column?
    - str, str, float64, float64
Are there any missing values?
    - nope, 55 non-null 

Which span of years is represented?
    - 1990/91 -> 2019/20

Which countries are included in the records?
    - production_df['Country'].unique()

In [4]:
production_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           55 non-null     str
 1   Coffee type       55 non-null     str
 2   1990/91           55 non-null     float64
 3   1991/92           55 non-null     float64
 4   1992/93           55 non-null     float64
 5   1993/94           55 non-null     float64
 6   1994/95           55 non-null     float64
 7   1995/96           55 non-null     float64
 8   1996/97           55 non-null     float64
 9   1997/98           55 non-null     float64
 10  1998/99           55 non-null     float64
 11  1999/00           55 non-null     float64
 12  2000/01           55 non-null     float64
 13  2001/02           55 non-null     float64
 14  2002/03           55 non-null     float64
 15  2003/04           55 non-null     float64
 16  2004/05           55 non-null     float64
 17  2005/06           55 non-null     float64
 18  2006/07           55 non-null     float64
 19  2007/08           55 non-null     float64
 20  2008/09           55 non-null     float64
 21  2009/10           55 non-null     float64
 22  2010/11           55 non-null     float64
 23  2011/12           55 non-null     float64
 24  2012/13           55 non-null     float64
 25  2013/14           55 non-null     float64
 26  2014/15           55 non-null     float64
 27  2015/16           55 non-null     float64
 28  2016/17           55 non-null     float64
 29  2017/18           55 non-null     float64
 30  2018/19           55 non-null     float64
 31  2019/20           55 non-null     float64
 32  Total_production  55 non-null     float64
dtypes: float64(31), str(2)
memory usage: 14.3 KB

In [5]:
production_df.isna().sum()

Country             0
Coffee type         0
1990/91             0
1991/92             0
1992/93             0
1993/94             0
1994/95             0
1995/96             0
1996/97             0
1997/98             0
1998/99             0
1999/00             0
2000/01             0
2001/02             0
2002/03             0
2003/04             0
2004/05             0
2005/06             0
2006/07             0
2007/08             0
2008/09             0
2009/10             0
2010/11             0
2011/12             0
2012/13             0
2013/14             0
2014/15             0
2015/16             0
2016/17             0
2017/18             0
2018/19             0
2019/20             0
Total_production    0
dtype: int64

In [6]:
production_df.shape
production_df.columns

production_df['Country'].unique()
production_df['Coffee type'].unique()

[col for col in production_df.columns if '/' in col]

['1990/91',
 '1991/92',
 '1992/93',
 '1993/94',
 '1994/95',
 '1995/96',
 '1996/97',
 '1997/98',
 '1998/99',
 '1999/00',
 '2000/01',
 '2001/02',
 '2002/03',
 '2003/04',
 '2004/05',
 '2005/06',
 '2006/07',
 '2007/08',
 '2008/09',
 '2009/10',
 '2010/11',
 '2011/12',
 '2012/13',
 '2013/14',
 '2014/15',
 '2015/16',
 '2016/17',
 '2017/18',
 '2018/19',
 '2019/20']

In [7]:
production_df['Country'].unique()

<StringArray>
[                          'Angola', 'Bolivia (Plurinational State of)',
                           'Brazil',                          'Burundi',
                          'Ecuador',                        'Indonesia',
                       'Madagascar',                           'Malawi',
                 'Papua New Guinea',                         'Paraguay',
                             'Peru',                           'Rwanda',
                      'Timor-Leste',                         'Zimbabwe',
                            'Congo',                             'Cuba',
               'Dominican Republic',                            'Haiti',
                      'Philippines',                         'Tanzania',
                           'Zambia',                         'Cameroon',
         'Central African Republic',                         'Colombia',
                       'Costa Rica',                    'Côte d'Ivoire',
     'Democratic Republic of Congo',                      'El Salvador',
                'Equatorial Guinea',                         'Ethiopia',
                            'Gabon',                            'Ghana',
                        'Guatemala',                           'Guinea',
                           'Guyana',                         'Honduras',
                            'India',                          'Jamaica',
                            'Kenya', 'Lao People's Democratic Republic',
                          'Liberia',                           'Mexico',
                            'Nepal',                        'Nicaragua',
                          'Nigeria',                           'Panama',
                     'Sierra Leone',                        'Sri Lanka',
                         'Thailand',                             'Togo',
                'Trinidad & Tobago',                           'Uganda',
                        'Venezuela',                         'Viet Nam',
                            'Yemen']
Length: 55, dtype: str

## Part 3 – Descriptive Statistics

The smallest total production values come from Equatorial Guinea, Nepal, Gabon, Congo, and Guyana. These countries produce extremely small volumes compared to major producers, often less than 1% of Brazil's output.

In [8]:
production_df[['Country', 'Total_production']].sort_values('Total_production', ascending=False).head()

      Country  Total_production
2      Brazil      7.508298e+10
53   Viet Nam      2.880318e+10
23   Colombia      2.159862e+10
5   Indonesia      1.540488e+10
29   Ethiopia      8.669520e+09

In [9]:
production_df[['Country', 'Total_production']].sort_values('Total_production', ascending=True).head()

              Country  Total_production
28  Equatorial Guinea         1080000.0
42              Nepal         1440000.0
30              Gabon         2700000.0
14              Congo         6900000.0
34             Guyana        10800000.0

In [10]:
stats = production_df.describe()

In [11]:
stats.loc[['min', 'max', 'mean']]

,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,1998/99,1999/00,...,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,Total_production
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.080000e+06
max,1.637160e+09,1.637580e+09,2.076180e+09,1.690020e+09,1.691520e+09,1.083600e+09,1.751820e+09,1.568880e+09,2.205660e+09,2.854680e+09,...,2.915520e+09,3.325080e+09,3.281340e+09,3.198300e+09,3.172260e+09,3.407280e+09,3.164400e+09,3.907860e+09,3.492660e+09,7.508298e+10
mean,1.017055e+08,1.104753e+08,1.074775e+08,1.001007e+08,1.017971e+08,9.525927e+07,1.127029e+08,1.089676e+08,1.187629e+08,1.433280e+08,...,1.541749e+08,1.649280e+08,1.679007e+08,1.639625e+08,1.703193e+08,1.770742e+08,1.785742e+08,1.881415e+08,1.800578e+08,4.104269e+09

## Part 4 – Data Quality Assessment

The production dataset appears to be high quality. There are no missing values across any of the 33 columns, and no duplicate rows were detected. All numerical columns use consistent float64 types, and the categorical fields (Country and Coffee type) are properly stored as strings. The year columns follow a uniform “YYYY/YY” format, which makes them easy to parse programmatically. Because the dataset is clean and well‑structured, it is unlikely to introduce bias or errors in downstream analysis.

In [12]:
production_df.isna().sum()

Country             0
Coffee type         0
1990/91             0
1991/92             0
1992/93             0
1993/94             0
1994/95             0
1995/96             0
1996/97             0
1997/98             0
1998/99             0
1999/00             0
2000/01             0
2001/02             0
2002/03             0
2003/04             0
2004/05             0
2005/06             0
2006/07             0
2007/08             0
2008/09             0
2009/10             0
2010/11             0
2011/12             0
2012/13             0
2013/14             0
2014/15             0
2015/16             0
2016/17             0
2017/18             0
2018/19             0
2019/20             0
Total_production    0
dtype: int64

In [13]:
production_df.duplicated().sum()

np.int64(0)

In [14]:
production_df.dtypes

Country                 str
Coffee type             str
1990/91             float64
1991/92             float64
1992/93             float64
1993/94             float64
1994/95             float64
1995/96             float64
1996/97             float64
1997/98             float64
1998/99             float64
1999/00             float64
2000/01             float64
2001/02             float64
2002/03             float64
2003/04             float64
2004/05             float64
2005/06             float64
2006/07             float64
2007/08             float64
2008/09             float64
2009/10             float64
2010/11             float64
2011/12             float64
2012/13             float64
2013/14             float64
2014/15             float64
2015/16             float64
2016/17             float64
2017/18             float64
2018/19             float64
2019/20             float64
Total_production    float64
dtype: object

In [15]:
production_df.groupby("Coffee type")["Total_production"].mean()

Coffee type
Arabica            2.634933e+09
Arabica/Robusta    1.208355e+10
Robusta            5.078520e+08
Robusta/Arabica    6.348012e+09
Name: Total_production, dtype: float64

## Part 5 – Initial Insights


Among the three datasets, the Coffee_production dataset appears to contain the most complete and consistent information. It includes 30 years of uninterrupted production data for 55 countries, with no missing values, no duplicates, and clean formatting. The structure is highly regular, making it ideal for time‑series analysis, trend detection, and comparative studies across nations.

The dataset most likely to require extensive cleaning is either Coffee_import or Coffee_export, depending on their formatting and completeness. These datasets often contain irregular country names, missing trade values, or inconsistent year ranges. Together, the three datasets can help a global coffee corporation answer strategic questions such as: Which countries are increasing or decreasing production over time? How do import and export patterns shift across regions? Which markets show growth potential, and where might supply risks emerge? These insights support decisions in sourcing, logistics, marketing, and long‑term planning.